### ISSUE TITLE
404 "Not Found"

### ISSUE THREAD

**Issue by olivierapex** [sous-chefs/snort#19]
### Cookbook version
4.0.0

### Chef-client version
chef-14.4.56-1

### Platform Details
CentOS 7

### Scenario:
On chef regular run, new instance node.

### Steps to Reproduce:
chef-client

### Expected Result:
Download version snort-2.9.11.1-1.centos7.x86_64.rpm

### Actual Result:
WARN: remote_file[/var/chef/cache/snort-2.9.11.1-1.centos7.x86_64.rpm] cannot be downloaded from https://www.snort.org/downloads/snort/snort-2.9.11.1-1.centos7.x86_64.rpm: 404 "Not Found"

### NOTE: 
Look like that the version 2.9.11.x have been removed from Snort Download repo, cannot found it anywhere.

### FIX:
please change line 46 of snort/cookbook/snort/install.rb for :
property :snort_version, String, default: '2.9.12-1'
:) 

### Temp Fix:
Quick temp fix is to wrap the cookbook and send value to "snort_version". Because there's no attributes for this cookbook ...

**Comment by Sliim** [comment]
The snort version can be specified from resource property:
```
snort_install 'default' do
  install_type 'compile'
  snort_version '2.9.12-1'
end
```

But yep, should be the default value since the old version is no longer available.
