### ISSUE TITLE
Default package checksum was not updated to match the new default version

### ISSUE THREAD

**Issue by simonwgill** [sous-chefs/snort#23]
### Cookbook version
4.0.0

### Chef-client version
14.7.17

### Platform Details
CentOS 7.5.1804

### Scenario:
Trying to install snort from a wrapper cookbook.

### Steps to Reproduce:
In metadata.rb

depends 'snort'

snort_install 'default' do
    snort_version '2.9.12-1'
end

### Expected Result:
For snort 2.9.12 to be downloaded from snort.org and installed

### Actual Result:
The remote_file resource in snort_install fails with an incorrect checksum error.

**Comment by Xorima** [comment]
can you issue a PR with the new checksum and we can get this sorted? :)

**Comment by simonwgill** [comment]
I can update the checksums. This will be my first contribution to a public cookbook though, so the rest of it I might be iffy on.

First time I've seen a Dangerfile too. Could that help prevent the same mistake happening again?

**Comment by Xorima** [comment]
We use the Dangerfile in a more generic manner, the tests should theoretically pick this up, which is a separate issue. 

In your PR just update the checksum and then add a note to the changelog, will try to get a patch released today for this

**Comment by Xorima** [comment]
This has been released now.
