### ISSUE TITLE
README: snort -h link is dead

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/snort#7]
I don't know what used to be here, but this link in the readme is dead:

http://blog.joelesler.net/2010/03/snort-h-doesnt-do-what-you-think-it-does.html

**Comment by josephholsten** [comment]
fixed by #9

**Comment by jtimberman** [comment]
I don't know what happened there, but the correct link appears to be: http://blog.joelesler.net/2010/03/snort-h-doesn-do-what-you-think-it-does.html
